import argparse

def createParser():
    parser = argparse.ArgumentParser(
        prog = "AH4-SDK build configurator",
        description = "--"
    )
    parser.add_argument(
        "--with-component",
        dest = "components",
        default = "",
        help = f"Component list"
    )
    parser.add_argument(
        "--debug",
        dest = "debug_en",
        action = 'store_true',
        default = False,
        help = "Enable debug building"
    )
    return parser

parser = createParser()
namespace = parser.parse_args()

component_action = 'build'
if namespace.debug_en:
    component_action = 'build-debug'

with open("Makefile.autogenerated", "w") as makefile:
    components = namespace.components.split(',')
    
    makefile.write('build:\n')

    for component in components:
        if component == 'icm42688':
            makefile.write(f'\tmake -C ./components/ICM42688_Barsotion/ {component_action}\n')
        elif component == 'icm45686':
            makefile.write(f'\tmake -C ./components/ICM45686_Barsotion/ clean {component_action}\n')
        else:
            pass
